# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'ITunesKit' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'ObjectMapper', '~> 2.2'
    pod 'SwiftLint', '~> 0.22'
    
    # Pods for ITunesKit
    target 'ITunesKitTests' do
        inherit! :search_paths
        # Pods for testing
    end
end
